version: '3.9'

services:
  backend:
    container_name: sesat_backend
    build:
      context: ./../sesat-backend/api
    environment:
      - SECRET_JWT=${SECRET_JWT}
      - SECRET_KEY=${SECRET_KEY}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_PORT=${DB_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    ports:
      - '3005:3005'
      
  # frontend:
  #   container_name: sesat_frontend
  #   build:
  #     context: ./../sesat-frontend
  #   environment:
  #     - NEXT_PUBLIC_SESAT_API_URL=${$NEXT_PUBLIC_SESAT_API_URL}
  #   ports:
  #     - '3000:3000'

  postgres-db:
    container_name: sesat_db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - 'sesat_master_data:/var/lib/postgresql/data'
    ports:
      - '${DB_FORWARDED_PORT}:5432'

volumes:
  sesat_master_data:
    driver: local